### ISSUE TITLE
Comparing this and Opencv implementation

### ISSUE THREAD

**Issue by saunair** [chalmersgit/EMD#1]
Hi, 
(This is not an issue of your code, but wanted to clarify things before using it)
I tried using the code and also tried the OpenCV EMD function, but got different results. 
Here is my code:(I also adjusted weights on your code to all of them to be 1)

from cv2 import *
import numpy as np

# Initialize a and b numpy arrays with coordinates and weights
a = np.asarray([[1,100, 40, 22], [1, 211, 20, 2 ], [1, 32, 190, 150 ], [ 1,2, 100, 100]], dtype=float)

b = np.asarray([[ 1,0, 0, 0 ], [1, 50, 100, 80 ], [1, 255, 255, 255 ]], dtype=float)

# Convert from numpy array to CV_32FC1 Mat
a64 = cv.fromarray(a)
a32 = cv.CreateMat(a64.rows, a64.cols, cv.CV_32FC1)
cv.Convert(a64, a32)
b64 = cv.fromarray(b)
b32 = cv.CreateMat(b64.rows, b64.cols, cv.CV_32FC1)
cv.Convert(b64, b32)

# Calculate Earth Mover's
print cv.CalcEMD2(a32,b32,cv.CV_DIST_L2)

# Wait for key
cv.WaitKey(0)

**Comment by chalmersgit** [comment]
Hi saunair, 

Thanks for your interest. I had a quick look into it.

I personally implemented this code to get a better understanding on how EMD works (so it may contain bugs and is not optimised!), and as I mentioned in my readme, this is based on the explanation by Rubner, and I compared my output with his c implementation too.

In your example, you changed the weights to 1.0. I did so as well, and here are the results:
Mine: 138.94567855
Ruber c implementation: 138.94567855
OpenCV3-Python: 104.20925903320312

I had a look at the source code for the EMD function for OpenCV located here:
https://github.com/opencv/opencv/blob/master/modules/imgproc/src/emd.cpp

And they say their method is "partially based on Yossi Rubner code". So it's interesting that we're both based on the same code but their implementation gets different results. Since it is "partially" based on it, they may have improved things. As far as I can tell, I've correctly implemented EMD, but there may be variations of it that I'm unaware of that produces different results.

It might be worth looking into other implementations to compare, or even reaching out to the OpenCV community ask them to check their implementation and ask why the output differs from the original Rubner c implementation.

Let me know if you find out any answers to this.

I hope this helps,
Thanks,
Andrew Chalmers


p.s for completeness, here is the code I used for the OpenCV implementation (just downloaded the latest version), running it with python 2.7. It works nicely with numpy arrays.

from cv2 import *
import numpy as np

# Initialize a and b numpy arrays with coordinates and weights (first element of each row is the weight)
a = np.asarray([[1.0,100, 40, 22], 
				[1.0, 211, 20, 2 ], 
				[1.0, 32, 190, 150 ], 
				[ 1.0,2, 100, 100]	], dtype=np.float32)

b = np.asarray([[ 1.0,0, 0, 0 ], 
				[1.0, 50, 100, 80 ], 
				[1.0, 255, 255, 255 ]], dtype=np.float32)
	
print cv2.EMD(a,b,cv2.DIST_L2)

**Comment by ChengTsang** [comment]
How to use this to compute the EMD between two histograms

**Comment by chalmersgit** [comment]
Hi @ChengTsang 
I've updated the code to show an example using histograms. 

To see it working, go to the main function and uncomment: 
doGaussianHistogramExample()

I should reiterate that my code is not designed to be fast. It's designed to be verbose so I could learn how EMD worked. I recommend using other packages like PyEMD or FastEMD if you want to use it in your projects.
